#!/bin/bash

# Use this script to encrypt fragments when submitting PRs to .eyaml files
# Secret goes to stdin, encrypted body goes to stdout
# Multiline secrets not supported

IFS= read -s -r SECRET
printf "ENC[PKCS7,%s]\n" "$(printf "%s" "$SECRET" | openssl smime -aes256 -encrypt -outform der -binary public_key.pkcs7.pem | openssl base64 -A)"
