---
fixtures:
  repositories:
    r10k: https://github.com/voxpupuli/puppet-r10k
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib
    grafana: https://github.com/voxpupuli/puppet-grafana
    apt: https://github.com/puppetlabs/puppetlabs-apt
    nginx: https://github.com/voxpupuli/puppet-nginx
    inifile: https://github.com/puppetlabs/puppetlabs-inifile
    systemd: https://github.com/voxpupuli/puppet-systemd
    concat: https://github.com/puppetlabs/puppetlabs-concat
    postgresql: https://github.com/puppetlabs/puppetlabs-postgresql
    dbbackup: https://github.com/voxpupuli/puppet-dbbackup
