---
fixtures:
  repositories:
    r10k: https://github.com/voxpupuli/puppet-r10k
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib
    grafana: https://github.com/voxpupuli/puppet-grafana
    apt: https://github.com/puppetlabs/puppetlabs-apt
