---
fixtures:
  repositories:
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib
    nginx: https://github.com/voxpupuli/puppet-nginx.git
    ferm: https://github.com/voxpupuli/puppet-ferm.git
    ssh: https://github.com/saz/puppet-ssh.git
    ssh_keygen: https://github.com/voxpupuli/puppet-ssh_keygen.git
    r10k: https://github.com/voxpupuli/puppet-r10k
    grafana: https://github.com/voxpupuli/puppet-grafana.git
    letsencrypt: https://github.com/voxpupuli/puppet-letsencrypt
    dbbackup: https://github.com/voxpupuli/puppet-dbbackup.git
    apt: https://github.com/puppetlabs/puppetlabs-apt
    inifile: https://github.com/puppetlabs/puppetlabs-inifile
    systemd: https://github.com/voxpupuli/puppet-systemd
    postgresql: https://github.com/puppetlabs/puppetlabs-postgresql
    puppetdb: https://github.com/puppetlabs/puppetlabs-puppetdb.git
    prometheus: https://github.com/voxpupuli/puppet-prometheus.git
    borg: https://github.com/voxpupuli/puppet-borg.git
    puppet: https://github.com/theforeman/puppet-puppet
    foreman: https://github.com/theforeman/puppet-foreman
    foreman_proxy: https://github.com/theforeman/puppet-foreman_proxy
    extlib: https://github.com/voxpupuli/puppet-extlib.git
    nftables: https://github.com/voxpupuli/puppet-nftables.git
    docker: https://github.com/puppetlabs/puppetlabs-docker
    libvirt: https://github.com/cirrax/puppet-libvirt
    redis: https://github.com/voxpupuli/puppet-redis.git
    choria: https://github.com/choria-io/puppet-choria
    augeasproviders_sysctl: https://github.com/voxpupuli/puppet-augeasproviders_sysctl
    archive: https://github.com/voxpupuli/puppet-archive
    augeas_core: https://github.com/puppetlabs/puppetlabs-augeas_core.git
    augeasproviders_core: https://github.com/voxpupuli/puppet-augeasproviders_core.git
    concat: https://github.com/puppetlabs/puppetlabs-concat
    cron: https://github.com/puppetlabs/puppetlabs-cron_core
    mcollective: https://github.com/choria-io/puppet-mcollective
    mcollective_agent_filemgr: https://github.com/choria-plugins/filemgr-agent
    mcollective_agent_package: https://github.com/choria-plugins/package-agent
    mcollective_agent_puppet: https://github.com/choria-plugins/puppet-agent
    mcollective_agent_service: https://github.com/choria-plugins/service-agent
    mcollective_choria: https://github.com/choria-plugins/mcollective_choria
    mcollective_util_actionpolicy: https://github.com/choria-plugins/action-policy
    mount: https://github.com/puppetlabs/puppetlabs-mount_core
    selinux_core: https://github.com/puppetlabs/puppetlabs-selinux_core
    ssh_keys: https://github.com/puppetlabs/puppetlabs-sshkeys_core
    yumrepo: https://github.com/puppetlabs/puppetlabs-yumrepo_core
