---
name: CI

on: pull_request

defaults:
  run:
    working-directory: ./site/profiles

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  setup_matrix:
    name: 'Setup Test Matrix'
    runs-on: ubuntu-latest
    timeout-minutes: 40
    outputs:
      puppet_unit_test_matrix: ${{ steps.get-outputs.outputs.puppet_unit_test_matrix }}
      github_action_test_matrix: ${{ steps.get-outputs.outputs.github_action_test_matrix }}
    env:
      BUNDLE_WITHOUT: development:system_tests:release
    steps:
      - uses: actions/checkout@v3
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          working-directory: ./site/profiles
      - name: Run static validations
        run: bundle exec rake validate lint check
      - name: Run rake rubocop
        run: bundle exec rake rubocop
      - name: Setup Test Matrix
        id: get-outputs
        run: bundle exec metadata2gha --use-fqdn --pidfile-workaround false

  unit:
    needs: setup_matrix
    runs-on: ubuntu-latest
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        include: ${{fromJson(needs.setup_matrix.outputs.puppet_unit_test_matrix)}}
    env:
      BUNDLE_WITHOUT: development:system_tests:release
      PUPPET_VERSION: "~> ${{ matrix.puppet }}.0"
    name: Puppet ${{ matrix.puppet }} (Ruby ${{ matrix.ruby }})
    steps:
      - uses: actions/checkout@v3
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ./site/profiles
      - name: Run tests
        run: bundle exec rake parallel_spec

  acceptance:
    needs: setup_matrix
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: development:test:release
    strategy:
      fail-fast: false
      matrix:
        include: ${{fromJson(needs.setup_matrix.outputs.github_action_test_matrix)}}
    name: ${{ matrix.puppet.name }} - ${{ matrix.setfile.name }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          working-directory: ./site/profiles
      - name: Run tests
        run: bundle exec rake beaker
        env:
          LANG: en_US
          LC_ALL: en_US.UTF-8
          BEAKER_PUPPET_COLLECTION: ${{ matrix.puppet.collection }}
          BEAKER_setfile: ${{ matrix.setfile.value }}

  puppetfile:
    defaults:
      run:
        working-directory: .
    runs-on: ubuntu-latest
    name: Validate Puppetfile + all modules
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
      - name: Check for puppetfile syntax correctness
        run: bundle exec rake r10k:syntax
      - name: validate URLs in Puppetfile
        run: bundle exec rake r10k:validate
      - name: Check for puppetfile duplicates
        run: bundle exec rake r10k:duplicates
      - name: Check for puppetfile module deprecations
        run: bundle exec rake r10k:deprecation
      - name: Check for outdated modules
        run: bundle exec rake r10k:dependencies
      - name: Validate all dependencies in metadata.json
        run: bundle exec rake metadata_deps
      - name: validate all dependencies
        run: bundle exec puppet module list --modulepath site

  Hiera:
    defaults:
      run:
        working-directory: .
    runs-on: ubuntu-latest
    name: Validate Hiera
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install --upgrade wheel setuptools pip
          pip install yamllint
      - name: Run yamllint
        run: yamllint --format github --strict data/
  tests:
    needs:
      - unit
      - acceptance
      - puppetfile
      - Hiera
    runs-on: ubuntu-latest
    name: Test suite
    steps:
      - run: echo Test suite completed
        # overwrite global working-directory because this step does not checkout the git repo
        working-directory: .
